version: "2"
services:
  app:
    image: ghcr.io/gissehel/arozos:latest
    volumes:
      - ./data/files:/arozos/src/files
      - ./data/tmp:/arozos/src/tmp
      - ./data/system:/arozos/src/system
    ports:
      - "8888:80"
      - "2121:21"
    restart: always
